<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */


?>
<?= $this->headScript()
    ->prependFile('https://code.jquery.com/jquery-3.7.1.min.js') ?>
<?= $this->partial('partials/flash_messages') ?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Desafio - Trafegus')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css')
        ->prependStylesheet('https://unpkg.com/tabulator-tables@5.4.4/dist/css/tabulator.min.css')
        ->prependStylesheet('https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css')
    ?>



    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <span class="navbar-text text-light">Desafio - Trafegus</span>
            </a>
            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a
                            class="nav-link active"
                            aria-current="page"
                            href="<?= $this->url('home') ?>">Homepage
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer class="fixed-bottom bg-light text-center text-dark-50 py-3">
            <p>
                &copy; <?= date('Y') ?>

            </p>
        </footer>
    </div>
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile('https://unpkg.com/tabulator-tables@5.4.4/dist/js/tabulator.min.js')
        ->prependFile('https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js');
    ?>

</body>

</html>