<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="container mt-4">
    <div class="row g-4 mt-4">
        <div class="col-md-4">
            <div class="card shadow-sm card-custom">
                <h5 class="card-header text-dark">Cadastro de Veículos</h5>
                <div class="card-body d-flex justify-content-center align-items-center h-100">
                    <a class="btn btn-outline-success" href="/veiculos">Visualizar &raquo;</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card shadow-sm card-custom">
                <h5 class="card-header text-dark">Cadastro de Motoristas</h5>
                <div class="card-body d-flex justify-content-center align-items-center h-100">
                    <a class="btn btn-outline-success" href="/motoristas">Visualizar &raquo;</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card shadow-sm card-custom">
                <h5 class="card-header text-dark">Rastreamento</h5>
                <div class="card-body d-flex justify-content-center align-items-center h-100">
                    <a class="btn btn-outline-success" href="/rastreamento">Visualizar &raquo;</a>
                </div>
            </div>
        </div>
    </div>
</div>